### ISSUE TITLE
feature request, support caller-defined cloudfront id so that ListDistributions access is not required

### ISSUE THREAD

**Issue by iambumblehead** [shouki-s/cloudfront-invalidate-cache#31]
I'm using buckets without cnames and am unable to use this script
```bash
Error: Distribution matching cname "a1b2c3d4e5f6g7.cloudfront.net" was not found.
    at invalidateCache (/root/.npm/_npx/c86231e800516906/node_modules/cloudfront-invalidate-cache/lib/index.js:14:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (/root/.npm/_npx/c86231e800516906/node_modules/cloudfront-invalidate-cache/index.js:22:5)
```

another bucket I use operates with [vue-cli-plugin-s3-deploy](https://www.npmjs.com/package/vue-cli-plugin-s3-deploy) and it does not require a cname but uses cloudfrontId instead. The policies required to use vue-cli-plugin-s3 are less permissive as well, which is an improvement for my case.

**Comment by shouki-s** [comment]
You can do it using aws cli.
Simply `aws Cloudfront create-invalidation --distribution-id XXXXXXXX`.
The purpose of cloudfront-invalidate-cache is to solve the problem that the aws cli does not support CNAME.
